In [1]:
from neutron_preprocessing import ExpProcessing
# pandas and numpy libraries are used in neutron_preprocessing

Экспериментальные распределения множественностей задаются в виде массива (например list() или np.array()) начиная с нулевой кратности. 
Вносить можно сколько угодно точек, внутри алгоритма автоматически данные будут расширены вплоть до 9й кратности.
Часто используемые данные приведены в комментариях. 

Алгоритм расчитает из измеренных точек ошибку измерений каждой кратности, вероятность испуская каждой кратности с ошибкой, среднее измеренное число нейтронов на распад с ошибкой, дисперсию распределения. Результат расчетов приводятся в виде pandas.DataFrame() и могут быть сохранены в виде .csv файла. Для подробностей можно вызвать help(ExpProcessing)

Experimental multiplicity distributions are specified as an array (e.g. list() or np.array()) starting from zero multiplicity. You can enter as many points as you want, inside the algorithm the data will automatically be expanded up to the 9th multiple. Frequently used data are given in the comments.

The algorithm will calculate error of each multiplicity of measurement, emission probability per multiplicity with error, mean  amount of neutrons per decay with error, variance of distribution from the measured points. The calculation result is given as pandas.DataFrame() and can be saved as a .csv file. For additional informations help(ExpProcessing) could be called.

In [2]:
# [12375, 25450, 20365, 8130, 1740, 215, 14, 1, 0] - Cm248
# [226, 548, 543, 280, 76, 21, 2] - No252
# [40, 84, 107, 75, 31, 1, 0] - No250 (5 us)
# [30, 56, 55, 31, 6, 2, 1] - No250 (36 us)
# [9, 36, 38, 30, 14, 3] - No254 (december only)
# [183, 319, 319, 271, 119, 29, 3, 1] - Rf256
# [24, 43, 34, 25, 12, 2] - Rf254
# [40, 81, 49, 34, 7, 1] - Fm244
# [224, 671, 986, 799, 408, 134, 34, 4] - No252 Sfinx 2021
# help(ExpProcessing)

In [4]:
experimental_spectra = [224, 671, 986, 799, 408, 134, 34, 4]
preprocessor = ExpProcessing(experimental_spectra)
preprocessor.get_data()

,bin,count,count_error,probability,probability_error,relative_error,mean,mean_error,variance
0,0,224,14.966630,0.068712,0.004591,0.066815,2.323313,0.048667,1.689334
1,1,671,25.903668,0.205828,0.007946,0.038605,2.323313,0.048667,1.689334
2,2,986,22.203603,0.302454,0.006811,0.022519,2.323313,0.048667,1.689334
3,3,799,16.319722,0.245092,0.005006,0.020425,2.323313,0.048667,1.689334
4,4,408,10.099505,0.125153,0.003098,0.024754,2.323313,0.048667,1.689334
5,5,134,5.176872,0.041104,0.001588,0.038633,2.323313,0.048667,1.689334
6,6,34,2.380476,0.010429,0.000730,0.070014,2.323313,0.048667,1.689334
7,7,4,0.755929,0.001227,0.000232,0.188982,2.323313,0.048667,1.689334
8,8,0,0.353553,0.000000,0.000108,inf,2.323313,0.048667,1.689334
9,9,0,0.333333,0.000000,0.000102,inf,2.323313,0.048667,1.689334

In [4]:
# saving to the .csv file
folder_name = "csv_data/"
file_name = "No252_2021_June_"
file_name += ".csv"
preprocessor.to_csv(folder_name + file_name)

csv_data/No252_2021_June.csv was saved successfully